# Generated by Django 4.1.6 on 2023-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_validity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
