# Generated by Django 4.1.6 on 2023-08-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='sender',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='status',
            field=models.CharField(choices=[('succeccful', 'succeccful'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
