# Generated by Django 4.1.6 on 2023-08-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpcode_sender_otpcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='sender',
            field=models.CharField(max_length=10),
        ),
    ]
