# Generated by Django 4.1.6 on 2023-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otpcode_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='sender',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
