# Generated by Django 4.1.6 on 2023-08-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_memebershiplan_alter_otpcode_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memebershiplan',
            old_name='name',
            new_name='title',
        ),
    ]
