# Generated by Django 4.1.6 on 2023-08-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_name_memebershiplan_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.AddField(
            model_name='user',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.memebershiplan'),
        ),
    ]
