# Generated by Django 4.1.6 on 2023-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_membership_user_membership_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.CharField(max_length=11, unique=True), max_length=15),
        ),
    ]
