# Generated by Django 4.1.6 on 2023-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_book_shabak'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
