# Generated by Django 4.1.6 on 2023-08-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottlingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=39)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('target', models.TextField()),
                ('throttled', models.BooleanField(default=False)),
                ('throttl_duration', models.IntegerField(default=0)),
            ],
        ),
    ]
