# Generated by Django 4.1.6 on 2023-08-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='throttlinglog',
            old_name='target',
            new_name='caller',
        ),
    ]
