# Generated by Django 4.1.6 on 2023-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throttling', '0002_rename_target_throttlinglog_caller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throttlinglog',
            name='caller',
            field=models.CharField(max_length=100),
        ),
    ]
